# -*- coding: utf-8 -*-
"""version2wavenet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V0Y9Uf-kzetvXBSZ8LBEl6L7I0qv1y5S
"""

import pandas as pd
import numpy as np
from torch.utils.data import DataLoader, Dataset
from sklearn.metrics import precision_recall_curve, precision_score, recall_score, f1_score
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt


# Load Data
train_df = pd.read_csv('/content/data/train.csv')
test_df = pd.read_csv('/content/data/test.csv')
labels_df = pd.read_csv('/content/data/test_label.csv')

# Normalize using training statistics
mean, std = train_df['TOTALDEMAND'].mean(), train_df['TOTALDEMAND'].std()
train_df['TOTALDEMAND'] = (train_df['TOTALDEMAND'] - mean) / std
test_df.iloc[:, 1] = (test_df.iloc[:, 1] - mean) / std


train_data = train_df['TOTALDEMAND'].values.astype(np.float32)
test_data = test_df.iloc[:, 1].values.astype(np.float32)
anomaly_labels = labels_df.iloc[:, 1].values.astype(int)  # Assuming first column contains labels


# Define Dataset Class
class TimeSeriesDataset(Dataset):
    def __init__(self, data, seq_len=55):
        self.data = data
        self.seq_len = seq_len

    def __len__(self):
        return len(self.data) - self.seq_len

    def __getitem__(self, index):
        x = self.data[index : index + self.seq_len]
        y = self.data[index + self.seq_len]
        return torch.tensor(x, dtype=torch.float32).unsqueeze(0), torch.tensor(y, dtype=torch.float32).unsqueeze(0)
# Hyperparameters
SEQ_LEN = 55
HIDDEN_DIM = 32
NUM_LAYERS = 10
LEARNING_RATE = 1e-3
BATCH_SIZE = 64
EPOCHS = 30

# Create DataLoaders
split = int(len(train_data) * 0.8)
train_dataset = TimeSeriesDataset(train_data[:split], seq_len=SEQ_LEN)
val_dataset = TimeSeriesDataset(train_data[split:], seq_len=SEQ_LEN)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)

# Device Configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

import torch
import torch.nn as nn
from torch.nn.utils import weight_norm

class GatedWaveNet(nn.Module):
    def __init__(self, in_channels=1, hidden_dim=32, num_layers=10, kernel_size=2, dilation_base=2, dropout=0.2):
        super().__init__()
        self.res_blocks = nn.ModuleList()
        self.gate_blocks = nn.ModuleList()
        self.skip_blocks = nn.ModuleList()
        self.dropout_blocks = nn.ModuleList()

        for i in range(num_layers):
            dilation = dilation_base ** i
            padding = (kernel_size - 1) * dilation
            in_ch = in_channels if i == 0 else hidden_dim

            self.res_blocks.append(weight_norm(nn.Conv1d(in_ch, hidden_dim, kernel_size, padding=padding, dilation=dilation)))
            self.gate_blocks.append(weight_norm(nn.Conv1d(in_ch, hidden_dim, kernel_size, padding=padding, dilation=dilation)))
            self.skip_blocks.append(weight_norm(nn.Conv1d(hidden_dim, hidden_dim, 1)))
            self.dropout_blocks.append(nn.Dropout(p=dropout))

        self.output_layer = nn.Linear(hidden_dim, 1)

    def forward(self, x):
        skip_sum = None
        for conv_f, conv_g, skip, drop in zip(self.res_blocks, self.gate_blocks, self.skip_blocks, self.dropout_blocks):
            f = torch.tanh(conv_f(x))
            g = torch.sigmoid(conv_g(x))
            out = drop(f * g)[..., :x.shape[-1]]
            skip_out = skip(out)
            skip_sum = skip_out if skip_sum is None else skip_sum + skip_out
            x = x + out if out.shape == x.shape else out

        out = torch.mean(skip_sum, dim=2)
        return self.output_layer(out).squeeze(1)

model = GatedWaveNet(in_channels=1, hidden_dim=HIDDEN_DIM, num_layers=NUM_LAYERS).to(device)
criterion = nn.SmoothL1Loss(beta=1.0)
optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, factor=0.5, patience=3)

best_val_loss = float("inf")
patience = 5
counter = 0

# Training
for epoch in range(EPOCHS):
    model.train()
    train_loss = 0.0
    for batch_x, batch_y in train_loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        optimizer.zero_grad()
        predictions = model(batch_x)
        loss = criterion(predictions, batch_y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        train_loss += loss.item()
    train_loss /= len(train_loader)

    # Validation
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for batch_x, batch_y in val_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            predictions = model(batch_x)
            val_loss += criterion(predictions, batch_y).item()
    val_loss /= len(val_loader)
    scheduler.step(val_loss)

    print(f"Epoch {epoch+1}/{EPOCHS} - Train Loss: {train_loss:.4f} - Val Loss: {val_loss:.4f}")

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), "best_model.pt")
        counter = 0
    else:
        counter += 1
        if counter >= patience:
            print("⏹️ Early stopping triggered.")
            break

print("✅ Training Complete!")

SEQ_LEN=48

# Prepare Test Dataset
test_dataset = TimeSeriesDataset(test_data, seq_len=SEQ_LEN)
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)

# Make Predictions
model.eval()
predictions = []
actual_values = test_data[SEQ_LEN:]
with torch.no_grad():
    for batch_x, _ in test_loader:
        batch_x = batch_x.to(device)
        pred = model(batch_x).cpu().item()
        predictions.append(pred)

# Convert to NumPy Arrays
predictions = np.array(predictions)
print(len(predictions))
actual_values = np.array(actual_values)
print(len(actual_values))
errors = np.abs(predictions - actual_values)

print("✅ Predictions aligned with actual values. Errors computed correctly!")

true_labels = labels_df.iloc[:, 1].values.astype(int)[SEQ_LEN:]

import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, average_precision_score

# Compute 90th percentile as the anomaly detection threshold
best_threshold = np.percentile(errors, 90)
print(f"✅ 90th Percentile Threshold Found: {best_threshold:.4f}")

# Anomaly Detection
anomalies = np.where(errors > best_threshold)[0]
print(f"📌 Detected Anomalies at indices: {anomalies}")

df_anomalies = pd.DataFrame(anomalies, columns=['Anomaly_Index'])
df_anomalies.to_csv("anomalies_indicesWavenet.csv", index=False)
print("📁 Anomaly indices saved to 'anomalies_indicesWavenet.csv'")

# Generate Predictions
pred_labels = np.zeros_like(true_labels)
pred_labels[anomalies] = 1

# Compute Metrics
precision = precision_score(true_labels, pred_labels)
recall = recall_score(true_labels, pred_labels)
f1 = f1_score(true_labels, pred_labels)
roc_auc = roc_auc_score(true_labels, errors)  # Using errors as the score
pr_auc = average_precision_score(true_labels, errors)  # Using errors as the score

print(f"📊 Precision: {precision:.4f}")
print(f"📊 Recall: {recall:.4f}")
print(f"📊 F1 Score: {f1:.4f}")
print(f"📊 ROC AUC: {roc_auc:.4f}")
print(f"📊 PR AUC: {pr_auc:.4f}")

model = GatedWaveNet(in_channels=1, hidden_dim=HIDDEN_DIM, num_layers=NUM_LAYERS).to(device)
criterion = nn.SmoothL1Loss(beta=1.0)
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, factor=0.5, patience=3)

best_val_loss = float("inf")
patience = 5
counter = 0

# Training
for epoch in range(EPOCHS):
    model.train()
    train_loss = 0.0
    for batch_x, batch_y in train_loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        optimizer.zero_grad()
        predictions = model(batch_x)
        loss = criterion(predictions, batch_y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        train_loss += loss.item()
    train_loss /= len(train_loader)

    # Validation
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for batch_x, batch_y in val_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            predictions = model(batch_x)
            val_loss += criterion(predictions, batch_y).item()
    val_loss /= len(val_loader)
    scheduler.step(val_loss)

    print(f"Epoch {epoch+1}/{EPOCHS} - Train Loss: {train_loss:.4f} - Val Loss: {val_loss:.4f}")

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), "best_model.pt")
        counter = 0
    else:
        counter += 1
        if counter >= patience:
            print("⏹️ Early stopping triggered.")
            break

print("✅ Training Complete!")

SEQ_LEN=48

# Prepare Test Dataset
test_dataset = TimeSeriesDataset(test_data, seq_len=SEQ_LEN)
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)

# Make Predictions
model.eval()
predictions = []
actual_values = test_data[SEQ_LEN:]
with torch.no_grad():
    for batch_x, _ in test_loader:
        batch_x = batch_x.to(device)
        pred = model(batch_x).cpu().item()
        predictions.append(pred)

# Convert to NumPy Arrays
predictions = np.array(predictions)
print(len(predictions))
actual_values = np.array(actual_values)
print(len(actual_values))
errors = np.abs(predictions - actual_values)

print("✅ Predictions aligned with actual values. Errors computed correctly!")

true_labels = labels_df.iloc[:, 1].values.astype(int)[SEQ_LEN:]

import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, average_precision_score

# Compute 90th percentile as the anomaly detection threshold
best_threshold = np.percentile(errors, 90)
print(f"✅ 90th Percentile Threshold Found: {best_threshold:.4f}")

# Anomaly Detection
anomalies = np.where(errors > best_threshold)[0]
print(f"📌 Detected Anomalies at indices: {anomalies}")

df_anomalies = pd.DataFrame(anomalies, columns=['Anomaly_Index'])
df_anomalies.to_csv("anomalies_indicesWavenet.csv", index=False)
print("📁 Anomaly indices saved to 'anomalies_indicesWavenet.csv'")

# Generate Predictions
pred_labels = np.zeros_like(true_labels)
pred_labels[anomalies] = 1

# Compute Metrics
precision = precision_score(true_labels, pred_labels)
recall = recall_score(true_labels, pred_labels)
f1 = f1_score(true_labels, pred_labels)
roc_auc = roc_auc_score(true_labels, errors)  # Using errors as the score
pr_auc = average_precision_score(true_labels, errors)  # Using errors as the score

print(f"📊 Precision: {precision:.4f}")
print(f"📊 Recall: {recall:.4f}")
print(f"📊 F1 Score: {f1:.4f}")
print(f"📊 ROC AUC: {roc_auc:.4f}")
print(f"📊 PR AUC: {pr_auc:.4f}")

import torch
import torch.nn as nn
import torch.nn.functional as F

class GatedWaveNetCPC(nn.Module):
    def __init__(self, in_channels=1, hidden_dim=32, num_layers=10, kernel_size=2,
                 dilation_base=2, use_gru_refiner=True, use_cpc=True, prediction_steps=5):
        super().__init__()
        self.use_gru_refiner = use_gru_refiner
        self.use_cpc = use_cpc
        self.prediction_steps = prediction_steps

        self.res_blocks = nn.ModuleList()
        self.gate_blocks = nn.ModuleList()
        self.skip_blocks = nn.ModuleList()

        for i in range(num_layers):
            dilation = dilation_base ** i
            padding = (kernel_size - 1) * dilation
            in_ch = in_channels if i == 0 else hidden_dim

            self.res_blocks.append(nn.Conv1d(in_ch, hidden_dim, kernel_size, padding=padding, dilation=dilation))
            self.gate_blocks.append(nn.Conv1d(in_ch, hidden_dim, kernel_size, padding=padding, dilation=dilation))
            self.skip_blocks.append(nn.Conv1d(hidden_dim, hidden_dim, 1))

        if self.use_gru_refiner:
            self.refiner = nn.GRU(hidden_dim, hidden_dim, batch_first=True)
        else:
            self.refiner = nn.Conv1d(hidden_dim, hidden_dim, kernel_size=3, padding=1)

        self.output_head = nn.Linear(hidden_dim, 1)

        if self.use_cpc:
            self.context_rnn = nn.GRU(hidden_dim, hidden_dim, batch_first=True)
            self.future_predictors = nn.ModuleList([
                nn.Linear(hidden_dim, hidden_dim) for _ in range(prediction_steps)
            ])

    def forward(self, x):
        skip_sum = None
        for conv_f, conv_g, skip in zip(self.res_blocks, self.gate_blocks, self.skip_blocks):
            f = torch.tanh(conv_f(x))
            g = torch.sigmoid(conv_g(x))
            out = f * g
            out = out[..., :x.shape[-1]]
            skip_out = skip(out)
            skip_sum = skip_out if skip_sum is None else skip_sum + skip_out
            x = x + out if out.shape == x.shape else out

        if self.use_gru_refiner:
            z_seq = skip_sum.permute(0, 2, 1)  # (B, T, C)
            _, h = self.refiner(z_seq)
            out = h[-1]
        else:
            out = self.refiner(skip_sum)
            out = torch.mean(out, dim=2)

        prediction = self.output_head(out).squeeze(1)

        if self.use_cpc:
            z_seq = skip_sum.permute(0, 2, 1)
            c_seq, _ = self.context_rnn(z_seq)
            return prediction, c_seq, z_seq
        else:
            return prediction, None, None

def info_nce_loss(z_context, z_future, future_predictors, K=5):
    loss = 0.0
    for k in range(K):
        if z_context.size(1) <= k + 1:
            continue
        pred = future_predictors[k](z_context[:, :-k-1])
        target = z_future[:, k+1:]
        sim = F.cosine_similarity(pred, target, dim=-1)
        labels = torch.ones_like(sim)
        loss += F.binary_cross_entropy_with_logits(sim, labels)
    return loss / K if K > 0 else torch.tensor(0.0, device=z_context.device)

alpha = 1.0
beta = 0.1
K = 5
model = GatedWaveNetCPC(
    in_channels=1,
    hidden_dim=HIDDEN_DIM,
    num_layers=NUM_LAYERS,
    kernel_size=2,
    dilation_base=2,
    use_gru_refiner=True,
    use_cpc=True,
    prediction_steps=5
).to(device)
criterion = nn.SmoothL1Loss(beta=1.0)
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, factor=0.5, patience=3)

best_val_loss = float("inf")
patience = 5
counter = 0

for epoch in range(EPOCHS):
    model.train()
    train_loss = 0.0

    for batch_x, batch_y in train_loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        optimizer.zero_grad()

        predictions, z_context, z_future = model(batch_x)
        reg_loss = criterion(predictions, batch_y)

        if z_context is not None and z_future is not None:
            cpc_loss = info_nce_loss(z_context, z_future, model.future_predictors, K=K)
            loss = alpha * reg_loss + beta * cpc_loss
        else:
            loss = reg_loss

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        train_loss += loss.item()

    train_loss /= len(train_loader)

    # Validation
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for batch_x, batch_y in val_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            predictions, *_ = model(batch_x)
            val_loss += criterion(predictions, batch_y).item()
    val_loss /= len(val_loader)
    scheduler.step(val_loss)

    print(f"Epoch {epoch+1}/{EPOCHS} - Train Loss: {train_loss:.4f} - Val Loss: {val_loss:.4f}")

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), "best_model.pt")
        counter = 0
    else:
        counter += 1
        if counter >= patience:
            print("⏹️ Early stopping triggered.")
            break

print("✅ Training Complete!")

SEQ_LEN=48

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, average_precision_score

# Load best model
model.load_state_dict(torch.load("best_model.pt"))
model.eval()

# Prepare test data
SEQ_LEN = 48
test_dataset = TimeSeriesDataset(test_data, seq_len=SEQ_LEN)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)
actual_values = test_data[SEQ_LEN:]

# Predict
predictions = []
with torch.no_grad():
    for batch_x, _ in test_loader:
        batch_x = batch_x.to(device)
        pred, _, _ = model(batch_x)  # Only use prediction head
        predictions.extend(pred.cpu().numpy())

predictions = np.array(predictions).flatten()
actual_values = np.array(actual_values).flatten()
errors = np.abs(predictions - actual_values)

# Threshold and anomalies
threshold = np.percentile(errors, 90)
anomalies = np.where(errors > threshold)[0]

# Save anomalies
pd.DataFrame(anomalies, columns=["Anomaly_Index"]).to_csv("anomalies_indices_GatedCPC.csv", index=False)

# Evaluation
true_labels = labels_df.iloc[:, 1].values.astype(int)[SEQ_LEN:]
pred_labels = np.zeros_like(true_labels)
pred_labels[anomalies] = 1

precision = precision_score(true_labels, pred_labels)
recall = recall_score(true_labels, pred_labels)
f1 = f1_score(true_labels, pred_labels)
roc_auc = roc_auc_score(true_labels, errors)
pr_auc = average_precision_score(true_labels, errors)

# Output
print(f"✅ Threshold: {threshold:.4f}")
print(f"📊 Precision : {precision:.4f}")
print(f"📊 Recall    : {recall:.4f}")
print(f"📊 F1 Score  : {f1:.4f}")
print(f"📊 ROC AUC   : {roc_auc:.4f}")
print(f"📊 PR AUC    : {pr_auc:.4f}")



import pandas as pd
import numpy as np
from torch.utils.data import DataLoader, Dataset
from sklearn.metrics import precision_recall_curve, precision_score, recall_score, f1_score
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt


# Load Data
train_df = pd.read_csv('/content/data/train.csv')
test_df = pd.read_csv('/content/data/test.csv')
labels_df = pd.read_csv('/content/data/test_label.csv')

# Normalize using training statistics
mean, std = train_df['TOTALDEMAND'].mean(), train_df['TOTALDEMAND'].std()
train_df['TOTALDEMAND'] = (train_df['TOTALDEMAND'] - mean) / std
test_df.iloc[:, 1] = (test_df.iloc[:, 1] - mean) / std


train_data = train_df['TOTALDEMAND'].values.astype(np.float32)
test_data = test_df.iloc[:, 1].values.astype(np.float32)
anomaly_labels = labels_df.iloc[:, 1].values.astype(int)  # Assuming first column contains labels


# Define Dataset Class
class TimeSeriesDataset(Dataset):
    def __init__(self, data, seq_len=55):
        self.data = data
        self.seq_len = seq_len

    def __len__(self):
        return len(self.data) - self.seq_len

    def __getitem__(self, index):
        x = self.data[index : index + self.seq_len]
        y = self.data[index + self.seq_len]
        return torch.tensor(x, dtype=torch.float32).unsqueeze(0), torch.tensor(y, dtype=torch.float32).unsqueeze(0)
# Hyperparameters
SEQ_LEN = 55
HIDDEN_DIM = 32
NUM_LAYERS = 10
LEARNING_RATE = 1e-3
BATCH_SIZE = 64
EPOCHS = 30

# Create DataLoaders
split = int(len(train_data) * 0.8)
train_dataset = TimeSeriesDataset(train_data[:split], seq_len=SEQ_LEN)
val_dataset = TimeSeriesDataset(train_data[split:], seq_len=SEQ_LEN)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)

# Device Configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

import torch
import torch.nn as nn
import torch.nn.functional as F

class GatedWaveNetWithRefiner(nn.Module):
    def __init__(self, in_channels=1, hidden_dim=32, num_layers=10,
                 kernel_size=2, dilation_base=2, dropout=0.2,
                 refiner_type='gru'):  # 'gru' or 'cnn'
        super().__init__()
        self.refiner_type = refiner_type.lower()
        assert self.refiner_type in ['gru', 'cnn'], "refiner_type must be 'gru' or 'cnn'"

        self.res_blocks = nn.ModuleList()
        self.gate_blocks = nn.ModuleList()
        self.skip_blocks = nn.ModuleList()
        self.dropout_blocks = nn.ModuleList()

        for i in range(num_layers):
            dilation = dilation_base ** i
            padding = (kernel_size - 1) * dilation
            in_ch = in_channels if i == 0 else hidden_dim

            self.res_blocks.append(nn.Conv1d(in_ch, hidden_dim, kernel_size, padding=padding, dilation=dilation))
            self.gate_blocks.append(nn.Conv1d(in_ch, hidden_dim, kernel_size, padding=padding, dilation=dilation))
            self.skip_blocks.append(nn.Conv1d(hidden_dim, hidden_dim, 1))
            self.dropout_blocks.append(nn.Dropout(p=dropout))

        if self.refiner_type == 'gru':
            self.refiner = nn.GRU(input_size=hidden_dim, hidden_size=hidden_dim,
                                  num_layers=1, batch_first=True)
        elif self.refiner_type == 'cnn':
            self.refiner = nn.Conv1d(hidden_dim, hidden_dim, kernel_size=3, padding=1)

        self.output_layer = nn.Linear(hidden_dim, 1)

    def forward(self, x):  # x shape: (B, C=1, T)
        skip_sum = None
        for conv_f, conv_g, skip, drop in zip(self.res_blocks, self.gate_blocks, self.skip_blocks, self.dropout_blocks):
            f = torch.tanh(conv_f(x))
            g = torch.sigmoid(conv_g(x))
            out = drop(f * g)[..., :x.shape[-1]]
            skip_out = skip(out)
            skip_sum = skip_out if skip_sum is None else skip_sum + skip_out
            x = x + out if out.shape == x.shape else out

        if self.refiner_type == 'gru':
            refined_input = skip_sum.permute(0, 2, 1)  # (B, T, C)
            _, h = self.refiner(refined_input)
            out = h[-1]  # Last GRU hidden state
        else:  # CNN refiner
            out = self.refiner(skip_sum)  # (B, C, T)
            out = torch.mean(out, dim=2)  # Global average pooling

        return self.output_layer(out).squeeze(1)  # (B

model = GatedWaveNetWithRefiner(
    in_channels=1,
    hidden_dim=64,
    num_layers=8,
    refiner_type='gru',  # or 'cnn'
).to(device)
criterion = nn.SmoothL1Loss(beta=1.0)
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, factor=0.5, patience=3)

best_val_loss = float("inf")
patience = 5
counter = 0

# Training
for epoch in range(EPOCHS):
    model.train()
    train_loss = 0.0
    for batch_x, batch_y in train_loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        optimizer.zero_grad()
        predictions = model(batch_x)
        loss = criterion(predictions, batch_y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        train_loss += loss.item()
    train_loss /= len(train_loader)

    # Validation
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for batch_x, batch_y in val_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            predictions = model(batch_x)
            val_loss += criterion(predictions, batch_y).item()
    val_loss /= len(val_loader)
    scheduler.step(val_loss)

    print(f"Epoch {epoch+1}/{EPOCHS} - Train Loss: {train_loss:.4f} - Val Loss: {val_loss:.4f}")

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), "best_model.pt")
        counter = 0
    else:
        counter += 1
        if counter >= patience:
            print("⏹️ Early stopping triggered.")
            break

print("✅ Training Complete!")

SEQ_LEN=48

# Prepare Test Dataset
SEQ_LEN=48
test_dataset = TimeSeriesDataset(test_data, seq_len=SEQ_LEN)
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)

# Make Predictions
model.eval()
predictions = []
actual_values = test_data[SEQ_LEN:]
with torch.no_grad():
    for batch_x, _ in test_loader:
        batch_x = batch_x.to(device)
        pred = model(batch_x).cpu().item()
        predictions.append(pred)

# Convert to NumPy Arrays
predictions = np.array(predictions)
print(len(predictions))
actual_values = np.array(actual_values)
print(len(actual_values))
errors = np.abs(predictions - actual_values)

print("✅ Predictions aligned with actual values. Errors computed correctly!")



true_labels = labels_df.iloc[:, 1].values.astype(int)[SEQ_LEN:]

15920

import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, average_precision_score

# Compute 90th percentile as the anomaly detection threshold
best_threshold = np.percentile(errors, 91)
print(f"✅ 90th Percentile Threshold Found: {best_threshold:.4f}")

# Anomaly Detection
anomalies = np.where(errors > best_threshold)[0]
print(f"📌 Detected Anomalies at indices: {anomalies}")

df_anomalies = pd.DataFrame(anomalies, columns=['Anomaly_Index'])
df_anomalies.to_csv("anomalies_indicesWavenet.csv", index=False)
print("📁 Anomaly indices saved to 'anomalies_indicesWavenet.csv'")

# Generate Predictions
pred_labels = np.zeros_like(true_labels)
pred_labels[anomalies] = 1

# Compute Metrics
precision = precision_score(true_labels, pred_labels)
recall = recall_score(true_labels, pred_labels)
f1 = f1_score(true_labels, pred_labels)
roc_auc = roc_auc_score(true_labels, errors)  # Using errors as the score
pr_auc = average_precision_score(true_labels, errors)  # Using errors as the score

print(f"📊 Precision: {precision:.4f}")
print(f"📊 Recall: {recall:.4f}")
print(f"📊 F1 Score: {f1:.4f}")
print(f"📊 ROC AUC: {roc_auc:.4f}")
print(f"📊 PR AUC: {pr_auc:.4f}")

import pandas as pd
import numpy as np
from torch.utils.data import DataLoader, Dataset
from sklearn.metrics import precision_recall_curve, precision_score, recall_score, f1_score
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt


# Load Data
train_df = pd.read_csv('/content/data2/train.csv')
test_df = pd.read_csv('/content/data2/test.csv')
labels_df = pd.read_csv('/content/data2/test_label.csv')

# Normalize using training statistics
mean, std = train_df['TOTALDEMAND'].mean(), train_df['TOTALDEMAND'].std()
train_df['TOTALDEMAND'] = (train_df['TOTALDEMAND'] - mean) / std
test_df.iloc[:, 1] = (test_df.iloc[:, 1] - mean) / std


train_data = train_df['TOTALDEMAND'].values.astype(np.float32)
test_data = test_df.iloc[:, 1].values.astype(np.float32)
anomaly_labels = labels_df.iloc[:, 1].values.astype(int)  # Assuming first column contains labels


# Define Dataset Class
class TimeSeriesDataset(Dataset):
    def __init__(self, data, seq_len=55):
        self.data = data
        self.seq_len = seq_len

    def __len__(self):
        return len(self.data) - self.seq_len

    def __getitem__(self, index):
        x = self.data[index : index + self.seq_len]
        y = self.data[index + self.seq_len]
        return torch.tensor(x, dtype=torch.float32).unsqueeze(0), torch.tensor(y, dtype=torch.float32).unsqueeze(0)
# Hyperparameters
SEQ_LEN = 55
HIDDEN_DIM = 32
NUM_LAYERS = 10
LEARNING_RATE = 1e-3
BATCH_SIZE = 64
EPOCHS = 30

# Create DataLoaders
split = int(len(train_data) * 0.8)
train_dataset = TimeSeriesDataset(train_data[:split], seq_len=SEQ_LEN)
val_dataset = TimeSeriesDataset(train_data[split:], seq_len=SEQ_LEN)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)

# Device Configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = GatedWaveNetWithRefiner(
    in_channels=1,
    hidden_dim=64,
    num_layers=8,
    refiner_type='gru',  # or 'cnn'
).to(device)
criterion = nn.SmoothL1Loss(beta=1.0)
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, factor=0.5, patience=3)

best_val_loss = float("inf")
patience = 5
counter = 0

# Training
for epoch in range(EPOCHS):
    model.train()
    train_loss = 0.0
    for batch_x, batch_y in train_loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        optimizer.zero_grad()
        predictions = model(batch_x)
        loss = criterion(predictions, batch_y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        train_loss += loss.item()
    train_loss /= len(train_loader)

    # Validation
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for batch_x, batch_y in val_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            predictions = model(batch_x)
            val_loss += criterion(predictions, batch_y).item()
    val_loss /= len(val_loader)
    scheduler.step(val_loss)

    print(f"Epoch {epoch+1}/{EPOCHS} - Train Loss: {train_loss:.4f} - Val Loss: {val_loss:.4f}")

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), "best_model.pt")
        counter = 0
    else:
        counter += 1
        if counter >= patience:
            print("⏹️ Early stopping triggered.")
            break

print("✅ Training Complete!")

SEQ_LEN=48

# Prepare Test Dataset
test_dataset = TimeSeriesDataset(test_data, seq_len=SEQ_LEN)
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)

# Make Predictions
model.eval()
predictions = []
actual_values = test_data[SEQ_LEN:]
with torch.no_grad():
    for batch_x, _ in test_loader:
        batch_x = batch_x.to(device)
        pred = model(batch_x).cpu().item()
        predictions.append(pred)

# Convert to NumPy Arrays
predictions = np.array(predictions)
print(len(predictions))
actual_values = np.array(actual_values)
print(len(actual_values))
errors = np.abs(predictions - actual_values)

print("✅ Predictions aligned with actual values. Errors computed correctly!")

true_labels = labels_df.iloc[:, 1].values.astype(int)[SEQ_LEN:]

import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, average_precision_score

# Compute 90th percentile as the anomaly detection threshold
best_threshold = np.percentile(errors, 90)
print(f"✅ 90th Percentile Threshold Found: {best_threshold:.4f}")

# Anomaly Detection
anomalies = np.where(errors > best_threshold)[0]
print(f"📌 Detected Anomalies at indices: {anomalies}")

df_anomalies = pd.DataFrame(anomalies, columns=['Anomaly_Index'])
df_anomalies.to_csv("anomalies_indicesWavenet.csv", index=False)
print("📁 Anomaly indices saved to 'anomalies_indicesWavenet.csv'")

# Generate Predictions
pred_labels = np.zeros_like(true_labels)
pred_labels[anomalies] = 1

# Compute Metrics
precision = precision_score(true_labels, pred_labels)
recall = recall_score(true_labels, pred_labels)
f1 = f1_score(true_labels, pred_labels)
roc_auc = roc_auc_score(true_labels, errors)  # Using errors as the score
pr_auc = average_precision_score(true_labels, errors)  # Using errors as the score

print(f"📊 Precision: {precision:.4f}")
print(f"📊 Recall: {recall:.4f}")
print(f"📊 F1 Score: {f1:.4f}")
print(f"📊 ROC AUC: {roc_auc:.4f}")
print(f"📊 PR AUC: {pr_auc:.4f}")



import pandas as pd
import numpy as np
from torch.utils.data import DataLoader, Dataset
from sklearn.metrics import precision_recall_curve, precision_score, recall_score, f1_score
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt


# Load Data
train_df = pd.read_csv('/content/data/train.csv')
test_df = pd.read_csv('/content/data/test.csv')
labels_df = pd.read_csv('/content/data/test_label.csv')

# Normalize using training statistics
mean, std = train_df['TOTALDEMAND'].mean(), train_df['TOTALDEMAND'].std()
train_df['TOTALDEMAND'] = (train_df['TOTALDEMAND'] - mean) / std
test_df.iloc[:, 1] = (test_df.iloc[:, 1] - mean) / std


train_data = train_df['TOTALDEMAND'].values.astype(np.float32)
test_data = test_df.iloc[:, 1].values.astype(np.float32)
anomaly_labels = labels_df.iloc[:, 1].values.astype(int)  # Assuming first column contains labels


# Define Dataset Class
class TimeSeriesDataset(Dataset):
    def __init__(self, data, seq_len=55):
        self.data = data
        self.seq_len = seq_len

    def __len__(self):
        return len(self.data) - self.seq_len

    def __getitem__(self, index):
        x = self.data[index : index + self.seq_len]
        y = self.data[index + self.seq_len]
        return torch.tensor(x, dtype=torch.float32).unsqueeze(0), torch.tensor(y, dtype=torch.float32).unsqueeze(0)
# Hyperparameters
SEQ_LEN = 55
HIDDEN_DIM = 32
NUM_LAYERS = 10
LEARNING_RATE = 1e-3
BATCH_SIZE = 64
EPOCHS = 20

# Create DataLoaders
split = int(len(train_data) * 0.8)
train_dataset = TimeSeriesDataset(train_data[:split], seq_len=SEQ_LEN)
val_dataset = TimeSeriesDataset(train_data[split:], seq_len=SEQ_LEN)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)

# Device Configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

import torch
import torch.nn as nn
import torch.nn.functional as F

class GatedWaveNetWithRefiner(nn.Module):
    def __init__(self, in_channels=1, hidden_dim=32, num_layers=10,
                 kernel_size=2, dilation_base=2, dropout=0.2,
                 refiner_type='gru'):  # 'gru' or 'cnn'
        super().__init__()
        self.refiner_type = refiner_type.lower()
        assert self.refiner_type in ['gru', 'cnn'], "refiner_type must be 'gru' or 'cnn'"

        self.res_blocks = nn.ModuleList()
        self.gate_blocks = nn.ModuleList()
        self.skip_blocks = nn.ModuleList()
        self.dropout_blocks = nn.ModuleList()

        for i in range(num_layers):
            dilation = dilation_base ** i
            padding = (kernel_size - 1) * dilation
            in_ch = in_channels if i == 0 else hidden_dim

            self.res_blocks.append(nn.Conv1d(in_ch, hidden_dim, kernel_size, padding=padding, dilation=dilation))
            self.gate_blocks.append(nn.Conv1d(in_ch, hidden_dim, kernel_size, padding=padding, dilation=dilation))
            self.skip_blocks.append(nn.Conv1d(hidden_dim, hidden_dim, 1))
            self.dropout_blocks.append(nn.Dropout(p=dropout))

        if self.refiner_type == 'gru':
            self.refiner = nn.GRU(input_size=hidden_dim, hidden_size=hidden_dim,
                                  num_layers=1, batch_first=True)
        elif self.refiner_type == 'cnn':
            self.refiner = nn.Conv1d(hidden_dim, hidden_dim, kernel_size=3, padding=1)

        self.output_layer = nn.Linear(hidden_dim, 1)

    def forward(self, x):  # x shape: (B, C=1, T)
        skip_sum = None
        for conv_f, conv_g, skip, drop in zip(self.res_blocks, self.gate_blocks, self.skip_blocks, self.dropout_blocks):
            f = torch.tanh(conv_f(x))
            g = torch.sigmoid(conv_g(x))
            out = drop(f * g)[..., :x.shape[-1]]
            skip_out = skip(out)
            skip_sum = skip_out if skip_sum is None else skip_sum + skip_out
            x = x + out if out.shape == x.shape else out

        if self.refiner_type == 'gru':
            refined_input = skip_sum.permute(0, 2, 1)  # (B, T, C)
            _, h = self.refiner(refined_input)
            out = h[-1]  # Last GRU hidden state
        else:  # CNN refiner
            out = self.refiner(skip_sum)  # (B, C, T)
            out = torch.mean(out, dim=2)  # Global average pooling

        return self.output_layer(out).squeeze(1)  # (B

model = GatedWaveNetWithRefiner(
    in_channels=1,
    hidden_dim=32,
    num_layers=3,
    refiner_type='gru',  # or 'cnn'
).to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, factor=0.5, patience=3)

best_val_loss = float("inf")
patience = 5
counter = 0

# Training
for epoch in range(EPOCHS):
    model.train()
    train_loss = 0.0
    for batch_x, batch_y in train_loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        optimizer.zero_grad()
        predictions = model(batch_x)
        loss = criterion(predictions, batch_y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        train_loss += loss.item()
    train_loss /= len(train_loader)

    # Validation
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for batch_x, batch_y in val_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            predictions = model(batch_x)
            val_loss += criterion(predictions, batch_y).item()
    val_loss /= len(val_loader)
    scheduler.step(val_loss)

    print(f"Epoch {epoch+1}/{EPOCHS} - Train Loss: {train_loss:.4f} - Val Loss: {val_loss:.4f}")

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), "best_model.pt")
        counter = 0
    else:
        counter += 1
        if counter >= patience:
            print("⏹️ Early stopping triggered.")
            break

print("✅ Training Complete!")

# Prepare Test Dataset
SEQ_LEN=48
test_dataset = TimeSeriesDataset(test_data, seq_len=SEQ_LEN)
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)

# Make Predictions
model.eval()
predictions = []
actual_values = test_data[SEQ_LEN:]
with torch.no_grad():
    for batch_x, _ in test_loader:
        batch_x = batch_x.to(device)
        pred = model(batch_x).cpu().item()
        predictions.append(pred)

# Convert to NumPy Arrays
predictions = np.array(predictions)
print(len(predictions))
actual_values = np.array(actual_values)
print(len(actual_values))
errors = np.abs(predictions - actual_values)

print("✅ Predictions aligned with actual values. Errors computed correctly!")

true_labels = labels_df.iloc[:, 1].values.astype(int)[SEQ_LEN:]

import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, average_precision_score

# Compute 90th percentile as the anomaly detection threshold
best_threshold = np.percentile(errors, 90)
print(f"✅ 90th Percentile Threshold Found: {best_threshold:.4f}")

# Anomaly Detection
anomalies = np.where(errors > best_threshold)[0]
print(f"📌 Detected Anomalies at indices: {anomalies}")

df_anomalies = pd.DataFrame(anomalies, columns=['Anomaly_Index'])
df_anomalies.to_csv("anomalies_indicesWavenet.csv", index=False)
print("📁 Anomaly indices saved to 'anomalies_indicesWavenet.csv'")

# Generate Predictions
pred_labels = np.zeros_like(true_labels)
pred_labels[anomalies] = 1

# Compute Metrics
precision = precision_score(true_labels, pred_labels)
recall = recall_score(true_labels, pred_labels)
f1 = f1_score(true_labels, pred_labels)
roc_auc = roc_auc_score(true_labels, errors)  # Using errors as the score
pr_auc = average_precision_score(true_labels, errors)  # Using errors as the score

print(f"📊 Precision: {precision:.4f}")
print(f"📊 Recall: {recall:.4f}")
print(f"📊 F1 Score: {f1:.4f}")
print(f"📊 ROC AUC: {roc_auc:.4f}")
print(f"📊 PR AUC: {pr_auc:.4f}")

import torch
import torch.nn as nn
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
from torch.utils.data import DataLoader, Dataset

# --------------------------- Dataset Preparation ---------------------------
class TimeSeriesDataset(Dataset):
    def __init__(self, data, seq_length):
        self.data = data
        self.seq_length = seq_length

    def __len__(self):
        return len(self.data) - self.seq_length

    def __getitem__(self, index):
        return (
            self.data[index:index + self.seq_length],
            self.data[index + self.seq_length]
        )

# --------------------------- LSTM Model ---------------------------
class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size=64, num_layers=1, num_classes=1):
        super(LSTMModel, self).__init__()
        self.lstm = nn.LSTM(input_size=input_size, hidden_size=hidden_size, num_layers=num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out_lstm, _ = self.lstm(x)
        out = self.fc(out_lstm[:, -1, :])
        return out

# --------------------------- Training Function ---------------------------
def train_model(model, train_loader, val_loader, criterion, optimizer, device, epochs=20, patience=5):
    model = model.to(device)
    best_model_state = None
    best_val_loss = float('inf')
    no_improvement_epochs = 0

    lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.1)

    for epoch in range(epochs):
        model.train()
        train_loss = 0

        for X, y in train_loader:
            X, y = X.float().to(device), y.float().to(device)
            optimizer.zero_grad()
            outputs = model(X)
            loss = criterion(outputs, y)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()

        train_loss /= len(train_loader)

        # Validation
        model.eval()
        val_loss = 0
        with torch.no_grad():
            for X, y in val_loader:
                X, y = X.float().to(device), y.float().to(device)
                outputs = model(X)
                loss = criterion(outputs, y)
                val_loss += loss.item()

        val_loss /= len(val_loader)

        print(f"Epoch {epoch + 1}/{epochs}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")

        # Early stopping
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_model_state = model.state_dict()
            no_improvement_epochs = 0
        else:
            no_improvement_epochs += 1

        if no_improvement_epochs >= patience:
            print("Early stopping")
            break

        lr_scheduler.step()

    model.load_state_dict(best_model_state)
    return model

# --------------------------- Prediction Function ---------------------------
def forecast_one_hour(model, data, seq_length, scaler, device):
    model.eval()
    predictions = []
    actual_values = []

    with torch.no_grad():
        for i in range(len(data) - seq_length - 2 + 1):
            input_seq = data[i:i + seq_length]
            actual_seq = data[i + seq_length:i + seq_length + 2]

            input_tensor = torch.tensor(input_seq, dtype=torch.float32).unsqueeze(0).unsqueeze(-1).to(device)

            step_predictions = []
            for _ in range(2):
                output = model(input_tensor).squeeze().item()
                step_predictions.append(output)
                input_seq = np.append(input_seq[1:], output)
                input_tensor = torch.tensor(input_seq, dtype=torch.float32).unsqueeze(0).unsqueeze(-1).to(device)

            predictions.append(step_predictions)
            actual_values.append(actual_seq)

    predictions = np.array(predictions)
    actual_values = np.array(actual_values)

    predictions = scaler.inverse_transform(predictions)
    actual_values = scaler.inverse_transform(actual_values)

    return predictions, actual_values

# --------------------------- Model Initialization and Training ---------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Initialize the model
model = LSTMModel(input_size=1, hidden_size=64, num_layers=1, num_classes=1).to(device)

# Define optimizer and loss function
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-5)

# Load data
data_path = '/content/data/train.csv'
data = pd.read_csv(data_path)
target_column = 'TOTALDEMAND'
train_size = int(0.8 * len(data))

train_data = data[:train_size]
val_data = data[train_size:]

scaler = MinMaxScaler()
train_data_scaled = scaler.fit_transform(train_data[[target_column]].values)
val_data_scaled = scaler.transform(val_data[[target_column]].values)

batch_size = 128
seq_length = 48
train_dataset = TimeSeriesDataset(train_data_scaled, seq_length)
val_dataset = TimeSeriesDataset(val_data_scaled, seq_length)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

# Train the model
model = train_model(model, train_loader, val_loader, criterion, optimizer, device, epochs=20, patience=5)

# Forecast
data_for_prediction = val_data_scaled.flatten()
predictions, actual_values = forecast_one_hour(model, data_for_prediction, seq_length, scaler, device)

import pandas as pd
import numpy as np

# Load your complete original test data
test_df = pd.read_csv('/content/data/test.csv')

# Load anomalies indices (relative to predictions starting from timestep 48)
anomalies_df = pd.read_csv('/content/anomalies_indicesWavenet (4).csv')
anomaly_indices = anomalies_df.iloc[:, 0].values.astype(int)

# Since anomalies are relative to timestep 48, shift indices explicitly by +48
anomaly_indices_corrected = anomaly_indices + 48

# Quick verification to ensure correct alignment explicitly
print("Verifying first few anomaly indices explicitly with timestamps:")
for idx in anomaly_indices[:5]:
    print(f"Anomaly idx from file: {idx}, Actual timestep in CSV: {idx+48}, Timestamp: {test_df.index[idx+48]}")

# Create a corrected copy of the entire test_df explicitly
corrected_df = test_df.copy()

# Set anomalies explicitly to NaN for interpolation (shifted indices!)
corrected_df.iloc[anomaly_indices + 48] = np.nan

# Interpolate explicitly after timestep 48
corrected_df.iloc[48:] = corrected_df.iloc[48:].interpolate(method='linear')

# Ensure no NaNs remain (fill boundary NaNs explicitly if any remain)
corrected_df.iloc[48:] = corrected_df.iloc[48:].fillna(method='ffill').fillna(method='bfill')

# Save explicitly corrected dataset
corrected_df.to_csv('test_file_corrected_interpolated_with_Refinedwavenet.csv')

print("✅ Anomaly interpolation explicitly performed and correctly matched after 48 timesteps.")

datatest_path = '/content/test_file_corrected_interpolated_with_Refinedwavenet.csv'
datatest = pd.read_csv(datatest_path)
target_column = 'TOTALDEMAND'

# Extract relevant column and scale data
scaler = MinMaxScaler()
test_data = scaler.fit_transform(datatest.iloc[:, 2].values.reshape(-1, 1))
test_dataf=test_data.flatten()

predictions, actual_values = forecast_one_hour(
    model=model,
    data=test_dataf,
    seq_length=48,
    scaler=scaler,
    device=device
)

mae = mean_absolute_error(actual_values, predictions)
mse = mean_squared_error(actual_values, predictions)

mae

mse

"""29avril"""

